### ISSUE TITLE
Resolution of ELBs can be cached by nginx

### ISSUE THREAD

**Issue by jmetzmeier** [pythian/opsviz#23]
Today I found kibana broken on an opsviz stack. This appeared to be caused by the ip changing on the ELB of the proxypass, but nginx was still trying to use the old IP. It looks like we can change the config to force DNS resolution everytime rather than caching the resolution:

http://serverfault.com/a/593003/105633

Another option may be to give the ELB an EIP.

**Comment by alexlovelltroy** [comment]
I wasn't aware we could use EIP for internal-only elbs.  Is that really supported?

**Comment by aaronmlee** [comment]
Not that I know of. ELBs publish a cname to which more or fewer end points are assigned based on load and geography; one must look up DNS when using them for this reason (IPs change unpredictably).



> On Jan 26, 2015, at 10:53 AM, Alex Lovell-Troy <notifications@github.com> wrote:
> 
> I wasn't aware we could use EIP for internal-only elbs. Is that really supported?
> 
> —
> Reply to this email directly or view it on GitHub.
> 

-- 


--

**Comment by alexlovelltroy** [comment]
Given what I'm reading, NGINX doesn't use the standard gethostbyname call because it is blocking and unpredictable.  Instead, it uses an internal resolver and it isn't clear to me how caching works in it.

http://hg.nginx.org/nginx/log/bcdfc39bf44d/src/core/ngx_resolver.c

It looks like adding a resolver-ip address to the proxy_pass section will trigger it to behave more like we expect with ttls and the like.  I'm working on a separate approach to this issue, but will also incorporate your changes because they make sense anyway.

**Comment by alexlovelltroy** [comment]
This is fixed in alovelltroy-bugfix
