### ISSUE TITLE
Multiple AZ

### ISSUE THREAD

**Issue by lesaux** [pythian/opsviz#51]
"Highly Available within one availability zone". For now I have just gone through some of the documentation, but it looks like support for multiple AZ would make sense, specifically when services are clustered.

**Comment by alexlovelltroy** [comment]
Absolutely.  Most people who are testing this out are only interested in it on a small scale.  We need an option that is more production quality.  It wouldn't be too hard to add the subnets, but we would need to figure out how to adjust cloudformation so that it didn't add instances in a second AZ unless requested.
